# Generated empirical patterns for missing meters
# Source: Golden dataset extraction
# Date: 2025-11-13

MISSING_METERS_PATTERNS = {
    # السريع (al-Sari')
    8: {
        'name_ar': 'السريع',
        'name_en': 'al-Sari'',
        'patterns': [
            '///o////o///o///////o////',
            '///o///o/////////o///o',
            '///o//o///o/o/o//o////',
            '///oo/o//o/o//o/o//o/o/',
            '//o///o//o//o///o//o/o',
            '//o///o/o/o//o///o//',
            '//o/o///o/o/o//o/////o',
            '//o/o//o//o/o//o/o/o//o//',
            '//o/o//o//o/o/o//o/o//o//',
            '//o/o//o/o/o//o///oo//o',
            '//o/o//o/oo/o//o///o/',
            '//o/o//o/oo/o//o//o//o',
            '//o/o/o/o//o//o//o//o',
            '//o/o/o/o/o//o/o//o///',
            '/o////////o//////o///',
            '/o////o/////////o////////',
            '/o////o//////o/o/o//////',
            '/o////o///o/o/////o///',
            '/o//o//o///o/o/o//oo///',
            '/o//o/o////o//o///o/o',
            '/o//o/o/o/o//o///o/o',
            '/o/o///o///o///o//o///o',
            '/o/o///o///o///o/o//o///o',
            '/o/o//o/////o/o//////',
            '/o/o//o///o//o/o//o//o////',
            '/o/o//o///o/o/o/o//o///o',
            '/o/o//o///ooo//////////',
            '/o/o//o//o//o//oo/o//o/////o//////o/',
            '/o/o//o/o//o/o/o/o//o/o/',
            '/o/o//o/o/o//o///o',
            '/o/o//o/o/o//o/o/o/o//o/o///o',
            '/o/o//o/o/o/o////o/o/o//o//o//',
            '/o/o/o//o/oo//o/o/o//o///',
            '/o/oo//o///o//oo/oo//oo',
        ]
    },
    # المديد (al-Madid)
    9: {
        'name_ar': 'المديد',
        'name_en': 'al-Madid',
        'patterns': [
            '///////////o//o//o///o///////////o/o',
            '////o/o//////o/////o/o//o////////////o//',
            '///o///o/o//////o///o/o///o//o////',
            '///o//o///o/o//o///o//',
            '//o/o////o///o//o/o',
            '//o/o//o/o/o//o//////o/o//o///o/o////////o//o/o',
            '//o/o//o/o/o//oo/o//o//o',
            '//o/o/o////o/o///o//o/o',
            '/o///o//o///o/////o////oo////////',
            '/o///o//o///o//o/o/',
            '/o///o//oo//o///o/o///////o//////o////o/o',
            '/o//o///o//o////////o////o///////o',
            '/o//o/o/o//////o/////////o//o//o/o',
            '/o/o//o////o//o///o///o/o////o//o//////o//',
            '/o/o//o///o/oo/o//o',
            '/o/o//o//o/o//o/o/o//o/',
            '/o/o//o/o/o//o//o///o//',
            '/o/o/o/o/o/o/////o',
            '/o/oo//o///o//o///o//',
            '/ooo//////o////o///o//o/o/o//o/o//////o////',
        ]
    },
    # المجتث (al-Mujtathth)
    10: {
        'name_ar': 'المجتث',
        'name_en': 'al-Mujtathth',
        'patterns': [
            '/o//o/o//o///o///o/o',
            '/o//o/o//o//o///o/',
            '/o//o/o//o//o/o/o//o/',
            '/o//o/o//o/o//o///o/o',
            '/o//o/o//oo//o///o///o',
            '/o//o/o/o//o//o/o//o/',
            '/o//o/o/o/o/o//o///o/',
            '/o//o/o/o/o/o//o/o//o',
            '/o/o////o//o/o/o//o/o/////////o',
            '/o/o///o//////o///o///o////',
            '/o/o//o////////o/o///////o/////',
            '/o/o//o///o/////o//o',
            '/o/o//o///o/o/o//o///o',
            '/o/o//o//o//o//o/////o////o/////o//o///o',
            '/o/o//o//o/o//o//oo/o//o',
            '/o/o//o/o////o/o///////o//o/o////o/o//////',
            '/o/o//o/o//o/o/o//o//o',
            '/o/o//o/o/o/o//////o/////////o/o',
            '/o/o/o//o/o//o///o///',
            '/oo//o/o/o//o/o/o//o/o',
        ]
    },
    # المنسرح (al-Munsarih)
    13: {
        'name_ar': 'المنسرح',
        'name_en': 'al-Munsarih',
        'patterns': [
            '/////o/o//o//o///o',
            '///o///o///o/////o/o///////////o',
            '///o//o//////oo//////o',
            '///o//o/o//////o///o',
            '///o/o/o//o///o//o/',
            '//o///o//o//o///o//o/o',
            '//o///o//o/o/o//o/o//o//oo',
            '//o/o//o///o//o/o/o//o///',
            '//o/o//o///o/o/o//o///',
            '/o////o/o//o/o///o/o/',
            '/o///o/o//o/o/o//o///',
            '/o//o////o/oo///o',
            '/o//o/o/oo//o//',
            '/o/o//o/////////o/////////o///o',
            '/o/o//o/////o//o////o',
            '/o/o//o///o//o//o//',
            '/o/o//o///o/oo/o//o///o',
            '/o/o//o/o//o////o////o',
            '/o/o//o/o/o/o//o///o',
            '/o/o//o/o/oo//o///o//o',
        ]
    },
    # المقتضب (al-Muqtadab)
    14: {
        'name_ar': 'المقتضب',
        'name_en': 'al-Muqtadab',
        'patterns': [
            '//////o/////oo///////o//o//o////oo///o//o/',
            '///o//o/o/o///o/o//o//o',
            '//o///o//o/o/o//o///o//o',
            '//o///o/o///o//o///o//',
            '//o///o/o/o//o/o//o//o',
            '//o//o/o//o/o/o/o//o///o//o',
            '//o/o//o//o/o/o//o/o//o//o',
            '//o/o//o//o/o/oo/o/o//o//o',
            '//o/o//o/o//o///o//o/o',
            '//o/o//o/o//o/o///o/o//o//o',
            '//o/o//o/o/o//o//o///o//',
            '//o/o//o/o/o//o/o//o//',
            '//o/o//o/o/o//o/o//o//o',
            '//o/o//o/o/o//o/oo//o/o//o',
            '//o/o//o/o/o/o//o///o//oo',
            '//o/o//o/oo/o//o/oo//o',
            '/o/o//////o/////o',
            '/o/o////o////o//o/o//o//o',
            '/o/o///o/o//o////o/o//o/o//',
            '/o/o///o/o//o/o/o//o///',
            '/o/o//o///o//o/o////o///o//////o/////////',
            '/o/o//o///o//o/o/o//o',
            '/o/o//o//o/o//o/o/o//o//o',
            '/o/o//o/o//o//o///o//',
            '/o/o//o/o//o//oo//o',
            '/o/o//o/o//o/o///o///////o/o////////o/o/o////o',
            '/o/o//o/o/o//o///o//o',
            '/o/o//o/o/o//o/o//o//o',
            '/ooo//o///o//o///o/ooo//o////o//////',
        ]
    },
    # المضارع (al-Mudari')
    15: {
        'name_ar': 'المضارع',
        'name_en': 'al-Mudari'',
        'patterns': [
            '////o//o////o///o/////////',
            '//o/////o//o///o//o',
            '//o////o////////o////o////o',
            '//o///o//o/o/o/o//o/o',
            '//o///o/o/o//o///o/o//o',
            '//o///o/o/o//o/o//o',
            '//o///o/o/o//oo/o//o//o//o',
            '//o///o/o/o/o//o///o//',
            '//o///o/o/o/o//o/o//o//o',
            '//o///o/oo/o//o/oo//o//o',
            '//o//o/o////o/o////o/////o//o',
            '//o/o///o/o//o///o//o',
            '//o/o//o///o/o//o///o//',
            '//o/o//o///oo/o/o//o///o',
            '//o/o//o/o//o//o///o//',
            '//o/o//o/o/o//o//o//o/o',
            '//o/o//o/o/o//o/o//o//o',
            '//o/o//o/o/o/o/o///o//o',
            '//o/o/o//o///o//o/',
            '//o/o/o//o/o/o//o///o//',
            '//o/o/o//o/o/oo//o/o//o//o',
            '/o////////o/o//o/o//o/o/o//o/o',
            '/o/o//o////o//o///o//o',
        ]
    },
    # المتدارك (al-Mutadarik)
    16: {
        'name_ar': 'المتدارك',
        'name_en': 'al-Mutadarik',
        'patterns': [
            '///o///o//o////o///o///o///o///',
            '//o///o//o//o///o/o//',
            '//o/o//o////oo//o/o//o//o//o/o//o/o/o///////////',
            '/o/////////o///o/o//////o/o/o///',
            '/o////o//o//o///o///o//////o',
            '/o////o/o//o/o//////ooo////o/o////',
            '/o///o/o//o///o/o////o////o',
            '/o//o/o//o/o//o/o//o',
            '/o//o/o/o/o//oo/o//oo//o/o/oo/o/oo/o/o/o',
            '/o/o////o//o///o/////',
            '/o/o///o/o///o//////o///o/o///o///',
            '/o/o///o/o/oo//o///o//o/o/o/o/o//o///o/o//o//o/o/o',
            '/o/o//o///o////o/o/oo//o/o/o///oo',
            '/o/o//o/o//o////o/o/o////o/o//oo//o',
            '/o/o//o/o//o//o/o//oo/o/o///o/o//o//o///oo',
            '/o/o//o/o/o//o/oo//o/oo/o//o/o//o/oo/o/o/o',
            '/o/o/o//o///o/////o//o/o/o//',
            '/o/o/o//o/o//o//oo/o//oo/o//o///o//o/o/o',
            '/o/o/o/o//o//o/o/o//o/oo/o/o//o///o///o//o/o/o//oo',
            '/o/o/oo//o///o/o///o/o/oo/////o',
            '/o/oo/o//o///o//o//o///o///o///o//o//o/',
        ]
    },
}

# Usage: Add these to EMPIRICAL_PATTERNS in detector_v2_hybrid.py
# EMPIRICAL_PATTERNS.update(MISSING_METERS_PATTERNS)